name: pull_down_button
description: Cupertino like pull-down button
version: 0.1.0
homepage: https://github.com/notDmDrl/pull_down_button

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=2.13.0-0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0